<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FodyHelpers" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="Verify.TUnit" />
  </ItemGroup>
</Project>
