<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <DisableFody>true</DisableFody>
    <Nullable>annotations</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="FodyHelpers" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="Verify.TUnit" />
    <ProjectReference Include="..\Janitor.Fody\Janitor.Fody.csproj" />
    <ProjectReference Include="..\Janitor\Janitor.csproj" />
    <ProjectReference Include="..\AssemblyToProcess\AssemblyToProcess.csproj" />
  </ItemGroup>
</Project>
